version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5001:5000"
    env_file: .env
    depends_on:
      - db

volumes:
  pgdata:
