version: "3.9"
services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../../.env
    volumes:
      - ../:/app
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=/backend
    volumes:
      - ../:/app
    networks:
      - app-network
    depends_on:
      - backend
# temporary changes
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
